import { BookOpenCheck, Database, ShieldCheck, AlertTriangle } from 'lucide-react'
const sections = [
  ['Hasil audit awal', Database, ['3.251 log Tahfizh tersedia; deposit resmi dan ujian Tahfizh masih kosong saat audit.', 'Enam template dan 57 item template Mutabaah tersedia, tetapi assignment template serta detail harian belum terisi.', 'Formula Tahfizh dan Mutabaah belum aktif ketika audit dilakukan.']],
  ['Aturan Tahfizh', BookOpenCheck, ['Pencapaian memakai ayat unik tervalidasi, bukan penjumlahan seluruh log.', 'Surah selesai hanya jika seluruh ayat surah telah tervalidasi.', 'Juz selesai tidak ditebak; diperlukan data juz lengkap/penanda tervalidasi.', 'Riwayat tetap terikat siswa, kelas, unit, semester, dan tahun ajaran.']],
  ['Aturan Mutabaah', ShieldCheck, ['Skor memakai bobot item template dari database.', 'Status NA/uzur dikeluarkan dari denominator.', 'Orang tua hanya dapat mengisi aktivitas yang menjadi tanggung jawab rumah.', 'Untuk Full Day, Zuhur dan Ashar dapat dikunci sebagai input sekolah; Subuh, Maghrib, Isya, Dhuha dan Tahajud diatur melalui aturan database.']],
  ['Ramadan dan operasional', AlertTriangle, ['Ramadan menggunakan periode bertanggal, bukan tebakan nama bulan.', 'Aturan periode Ramadan mengalahkan aturan reguler.', 'Tarawih, Witir, puasa, tadarus dan target lain harus dimasukkan ke master/template sebelum digunakan.', 'Tidak ada formula, target, atau hasil nilai contoh yang dipaksakan.']],
]
export default function AssessmentImplementationNotesPage(){return <div className="space-y-5"><div className="rounded-[22px] border-2 border-sky-500/20 bg-gradient-to-r from-sky-50 to-white p-5 dark:bg-slate-900"><h2 className="text-xl font-black">Catatan Implementasi Penilaian</h2><p className="mt-1 text-xs text-slate-500">Dokumentasi audit, aturan bisnis, batasan data, dan cara kerja Tahfizh–Mutabaah. Terakhir diperbarui 4 September 2026.</p></div><div className="grid gap-4 md:grid-cols-2">{sections.map(([title,Icon,items])=><section key={title} className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><div className="flex items-center gap-2"><Icon className="h-5 w-5 text-emerald-700"/><h3 className="font-black">{title}</h3></div><ul className="mt-3 space-y-2 text-xs leading-5 text-slate-600 dark:text-slate-300">{items.map(x=><li key={x} className="flex gap-2"><span className="text-emerald-600">•</span><span>{x}</span></li>)}</ul></section>)}</div><section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-xs text-amber-900"><h3 className="font-black">Urutan penggunaan</h3><ol className="mt-2 list-decimal space-y-1 pl-5"><li>Tetapkan program unit/kelas.</li><li>Buat periode reguler atau Ramadan.</li><li>Siapkan aktivitas dan template Mutabaah.</li><li>Atur pencatat dan lokasi setiap aktivitas.</li><li>Buat serta aktifkan formula penilaian.</li><li>Guru memfinalisasi data sekolah; orang tua mengisi bagian rumah yang diizinkan.</li></ol></section></div>}

