import { useEffect, useState } from 'react'
import { CalendarDays, Save, ShieldCheck } from 'lucide-react'
import { worshipAssessmentSettingService as service } from '../services/worshipAssessmentSettingService'

const input = 'mt-1 w-full rounded-xl border border-slate-200 bg-white p-2.5 text-xs dark:border-slate-700 dark:bg-slate-800'
export default function WorshipAssessmentSettingPage() {
  const [data, setData] = useState({ programs: [], periods: [], rules: [] }); const [options, setOptions] = useState({ units: [], classes: [], academic_years: [], semesters: [], templates: [], agenda_items: [] })
  const [message, setMessage] = useState(''); const [error, setError] = useState('')
  const [program, setProgram] = useState({ education_unit_id: '', class_id: '', program_type: 'fullday', school_weekdays: [1,2,3,4,5], is_active: true })
  const [period, setPeriod] = useState({ name: '', period_type: 'ramadan', scope: 'unit', education_unit_id: '', class_id: '', academic_year_id: '', semester_id: '', template_id: '', start_date: '', end_date: '', priority: 100, is_active: true })
  const [rule, setRule] = useState({ assessment_period_id: '', agenda_item_id: '', program_type: 'fullday', input_source: 'parent', location: 'home', school_day_only: false, requires_verification: true, priority: 10, is_active: true })
  const load = async () => { try { const [a,b] = await Promise.all([service.list(), service.options()]); setData(a.data); setOptions(b.data); const unit=b.data.units[0]?.id||''; const year=b.data.academic_years.find(x=>x.is_active)?.id||b.data.academic_years[0]?.id||''; setProgram(v=>({...v,education_unit_id:v.education_unit_id||unit})); setPeriod(v=>({...v,education_unit_id:v.education_unit_id||unit,academic_year_id:v.academic_year_id||year})); } catch(e){setError(e.response?.data?.message||'Pengaturan gagal dimuat.')} }
  useEffect(()=>{load()},[])
  const save = async (fn,payload) => { setError(''); setMessage(''); try { await fn(Object.fromEntries(Object.entries(payload).map(([k,v])=>[k,v===''?null:v]))); setMessage('Konfigurasi tersimpan di database.'); await load() } catch(e){setError(e.response?.data?.message||Object.values(e.response?.data?.errors||{})?.[0]?.[0]||'Konfigurasi gagal disimpan.')} }
  return <div className="space-y-5">
    <div className="rounded-[22px] border-2 border-emerald-500/20 bg-gradient-to-r from-emerald-50 to-white p-5 dark:bg-slate-900"><div className="flex gap-3"><ShieldCheck className="h-9 w-9 text-emerald-700"/><div><h2 className="text-lg font-black">Program & Penilaian Ibadah</h2><p className="text-xs text-slate-500">Atur Full Day, periode Ramadan, dan pembagian input sekolah–rumah tanpa hardcode.</p></div></div></div>
    {(message||error)&&<div className={`rounded-xl p-3 text-xs font-bold ${error?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700'}`}>{error||message}</div>}
    <div className="grid gap-4 xl:grid-cols-3">
      <form onSubmit={e=>{e.preventDefault();save(service.createProgram,program)}} className="rounded-2xl border bg-white p-4 dark:bg-slate-900"><h3 className="font-black">1. Program Unit/Kelas</h3><label className="text-xs font-bold">Unit<select required className={input} value={program.education_unit_id} onChange={e=>setProgram({...program,education_unit_id:e.target.value,class_id:''})}>{options.units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-xs font-bold">Kelas (opsional)<select className={input} value={program.class_id} onChange={e=>setProgram({...program,class_id:e.target.value})}><option value="">Semua kelas</option>{options.classes.filter(x=>x.unit_pendidikan_id===program.education_unit_id).map(x=><option key={x.id} value={x.id}>{x.nama_kelas}</option>)}</select></label><label className="text-xs font-bold">Jenis program<select className={input} value={program.program_type} onChange={e=>setProgram({...program,program_type:e.target.value})}>{['fullday','regular','boarding','tahfizh'].map(x=><option key={x}>{x}</option>)}</select></label><button className="mt-4 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white"><Save className="mr-1 inline h-4 w-4"/>Simpan</button></form>
      <form onSubmit={e=>{e.preventDefault();save(service.createPeriod,period)}} className="rounded-2xl border bg-white p-4 dark:bg-slate-900"><h3 className="font-black">2. Periode Ramadan/Reguler</h3><label className="text-xs font-bold">Nama<input required className={input} value={period.name} onChange={e=>setPeriod({...period,name:e.target.value})}/></label><div className="grid grid-cols-2 gap-2"><label className="text-xs font-bold">Mulai<input required type="date" className={input} value={period.start_date} onChange={e=>setPeriod({...period,start_date:e.target.value})}/></label><label className="text-xs font-bold">Selesai<input required type="date" className={input} value={period.end_date} onChange={e=>setPeriod({...period,end_date:e.target.value})}/></label></div><label className="text-xs font-bold">Unit<select required className={input} value={period.education_unit_id} onChange={e=>setPeriod({...period,education_unit_id:e.target.value})}>{options.units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-xs font-bold">Template<select className={input} value={period.template_id} onChange={e=>setPeriod({...period,template_id:e.target.value})}><option value="">Template assignment aktif</option>{options.templates.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="mt-4 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white"><CalendarDays className="mr-1 inline h-4 w-4"/>Simpan</button></form>
      <form onSubmit={e=>{e.preventDefault();save(service.createRule,rule)}} className="rounded-2xl border bg-white p-4 dark:bg-slate-900"><h3 className="font-black">3. Tanggung Jawab Input</h3><label className="text-xs font-bold">Periode<select className={input} value={rule.assessment_period_id} onChange={e=>setRule({...rule,assessment_period_id:e.target.value})}><option value="">Aturan reguler</option>{data.periods.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-xs font-bold">Aktivitas<select required className={input} value={rule.agenda_item_id} onChange={e=>setRule({...rule,agenda_item_id:e.target.value})}><option value="">Pilih aktivitas</option>{options.agenda_items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><label className="text-xs font-bold">Pencatat<select className={input} value={rule.input_source} onChange={e=>setRule({...rule,input_source:e.target.value})}>{['parent','school','either','student','supervisor'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-bold">Lokasi<select className={input} value={rule.location} onChange={e=>setRule({...rule,location:e.target.value})}>{['home','school','any'].map(x=><option key={x}>{x}</option>)}</select></label></div><button className="mt-4 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white"><Save className="mr-1 inline h-4 w-4"/>Simpan</button></form>
    </div>
    <div className="rounded-2xl border bg-white p-4 text-xs dark:bg-slate-900"><h3 className="font-black">Konfigurasi tersimpan</h3><p className="mt-2 text-slate-500">{data.programs.length} program · {data.periods.length} periode · {data.rules.length} aturan tanggung jawab.</p></div>
  </div>
}

